Docker 2
Otus-DevOps-2018-05/valmanmsk_microservices pull request #2
Opened 2018-07-27 10:05 UTC by valmanmsk

# Выполнено ДЗ № 14

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
- Создал новый проект doker на GCE
- Установил docker-machine
- Создал Docker-host с помощью docker-machine
- Создал файлы Dockerfile, mongod.conf, db_config и start.sh
- Собрал образ
- Запустил контейнер из этого образа
- Зарегистрировался на Docker Hub
- Загрузил на него образ
- Запустил контейнер из образа на Docker Hub

## Задание со *

- Создал конфигурационные файлы Terraform, для создания инстансов в GCE
- Создал плейбуки Ansible для установки docker-ce и запуска контейнера из своего образа на Docker Hub
- Создал шаблон Packer для создания образа с установленным docker-ce в GCE

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-08-17 12:41 UTC, virtualshuric requested changes
Задание со звездочкой не выполнено (см. комментарии по коду, также для Ansible необходим рабочий вариант dynamic inventory). Тут уже по желанию - или поправить или зачтем без *ки

2018-08-17 12:41 UTC, virtualshuric commented on docker-monolith/infra/ansible/inventory.sh
> +#!/bin/bash
Это не динамический инвентори. А скрипт-заглушка, вдобавок с ошибкой. Уж лучше использовать gce.py

2018-08-17 12:41 UTC, virtualshuric commented on docker-monolith/infra/packer/immutable.json
> +            "script": "scripts/install_docker.sh",
Для задания со звездочкой, необходимо конфигурацию образа ВМ с помощью Ansible

2018-08-21 14:34 UTC, valmanmsk commented
Давайте без звездочки. Что-то работы навалило, некогда ДЗ новые сделать, не говоря уж об исправлении старых.

2018-08-24 14:59 UTC, valmanmsk reviewed
Пусть без звездочки будет.

2018-08-27 13:05 UTC, virtualshuric approved these changes

2018-08-27 13:07 UTC, merged